// Mascot sprites (64x64 RGB565, 0xF81F = transparent). Generated by host/gen_sprite.py.
#pragma once
#include "sprite_bot_working.h"
#include "sprite_bot_done.h"
#include "sprite_bot_ask.h"
#include "sprite_bot_idle.h"
#include "sprite_bot_outage.h"
#include "sprite_bot_limited.h"
#include "sprite_bot_nolink.h"
#define SPRITE_SZ 64
#define SPRITE_KEY 0xF81F
