#!/usr/bin/env python3
"""Embed the host files in the firmware, so a new Mac needs nothing but curl.

install.sh reads two things out of the repo at runtime: the hook it copies into
~/.claude/hooks, and the daemon the service points at. Everything else it writes
itself. Serve those two plus install.sh from the board and enrolling a machine stops
needing git, GitHub, or a checkout at all.

Run this whenever any of the three change, then reflash. The board serves whatever
firmware it is running, so a stale header means a stale install.

    python3 host/gen_payload.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "firmware", "claude_status", "payload.h")
DELIM = "ESP32PAYLOAD"

FILES = [
    ("PAYLOAD_INSTALL", "host/install.sh"),
    ("PAYLOAD_HOOK", "host/esp32-status-hook.sh"),
    ("PAYLOAD_DAEMON", "host/claude_status_daemon.py"),
]


def main():
    parts = [
        "// Generated by host/gen_payload.py. Do not edit.",
        "//",
        "// The host files, served by the board so a new Mac needs only curl. Raw string",
        "// literals: the content goes in byte for byte, with no escaping to get wrong.",
        "#pragma once",
        "",
    ]
    total = 0
    for name, rel in FILES:
        body = open(os.path.join(ROOT, rel), "rb").read().decode()
        if f'){DELIM}"' in body:
            sys.exit(f"{rel} contains the raw-literal delimiter; pick another")
        total += len(body.encode())
        parts.append(f'// {rel}, {len(body.encode())} bytes')
        parts.append(f'static const char {name}[] PROGMEM = R"{DELIM}({body}){DELIM}";')
        parts.append("")
    open(OUT, "w").write("\n".join(parts))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(FILES)} files, {total} bytes of flash")


if __name__ == "__main__":
    main()
