#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow>=10"]
# ///
"""Generate a pixel-art sprite with Gemini and convert it to an RGB565 C header.

usage: gen_sprite.py NAME SIZE "prompt"   (reads GEMINI_API_KEY from .env.local)
Writes host/sprites/NAME.png (raw), NAME_SIZE.png (downscaled) and firmware/claude_status/sprite_NAME.h
"""
import base64, json, os, sys, urllib.request
from PIL import Image, ImageChops

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL = os.environ.get("GEMINI_IMAGE_MODEL", "gemini-2.5-flash-image")


def api_key():
    if os.environ.get("GEMINI_API_KEY"):
        return os.environ["GEMINI_API_KEY"]
    for line in open(os.path.join(ROOT, ".env.local")):
        if line.startswith("GEMINI_API_KEY="):
            return line.split("=", 1)[1].strip().strip('"')
    sys.exit("GEMINI_API_KEY not found")


def generate(prompt, out_png):
    body = {"contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"responseModalities": ["IMAGE"]}}
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent"
    req = urllib.request.Request(url, data=json.dumps(body).encode(),
                                 headers={"Content-Type": "application/json", "x-goog-api-key": api_key()})
    with urllib.request.urlopen(req, timeout=120) as r:
        resp = json.load(r)
    for part in resp["candidates"][0]["content"]["parts"]:
        if "inlineData" in part:
            open(out_png, "wb").write(base64.b64decode(part["inlineData"]["data"]))
            return
    sys.exit(f"no image in response: {json.dumps(resp)[:400]}")


def clean(im, bg, tol=48):
    """Quantize away generation noise and force near-bg pixels to exact bg."""
    im = im.quantize(16, method=Image.Quantize.MEDIANCUT).convert("RGB")
    px, (w, h) = im.load(), im.size
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if abs(r - bg[0]) + abs(g - bg[1]) + abs(b - bg[2]) < tol:
                px[x, y] = bg
    return im


def block_size(im):
    """Source pixel-art block size = most common horizontal run length in 4..80."""
    from collections import Counter
    px, (w, h) = im.load(), im.size
    c = Counter()
    for y in range(h):
        run, prev = 1, px[0, y]
        for x in range(1, w):
            if px[x, y] == prev:
                run += 1
            else:
                if 4 <= run <= 80: c[run] += 1
                run, prev = 1, px[x, y]
    return c.most_common(1)[0][0] if c else 1


def to_rgb565_header(png, size, name, out_h, bg=(0, 0, 0)):
    im = clean(Image.open(png).convert("RGB"), bg)
    bbox = ImageChops.difference(im, Image.new("RGB", im.size, bg)).getbbox()
    im = im.crop(bbox) if bbox else im
    b = block_size(im)
    cols, rows = max(1, round(im.width / b)), max(1, round(im.height / b))
    grid = im.resize((cols, rows), Image.BOX)          # one sample per source block
    scale = (size - 2) / max(cols, rows)          # fill the box (blocks may be uneven by a pixel)
    art = grid.resize((max(1, int(cols * scale)), max(1, int(rows * scale))), Image.NEAREST)
    canvas = Image.new("RGB", (size, size), bg)
    canvas.paste(art, ((size - art.width) // 2, (size - art.height) // 2))
    canvas.save(png.replace(".png", f"_{size}.png"))
    px = canvas.load()
    words = []
    for y in range(size):
        for x in range(size):
            r, g, bl = px[x, y]
            # background pixels become the transparent key colour 0xF81F (pure magenta)
            words.append(0xF81F if (r, g, bl) == bg else ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (bl >> 3))
    with open(out_h, "w") as f:
        f.write(f"// generated by host/gen_sprite.py: {name} {size}x{size} RGB565 (block={b}, grid={cols}x{rows})\n#pragma once\n#include <stdint.h>\n")
        f.write(f"#define SPRITE_{name.upper()}_W {size}\n#define SPRITE_{name.upper()}_H {size}\n")
        f.write(f"static const uint16_t sprite_{name}[{size * size}] PROGMEM = {{\n")
        for i in range(0, len(words), 12):
            f.write("  " + ", ".join(f"0x{w:04X}" for w in words[i:i + 12]) + ",\n")
        f.write("};\n")
    print(f"block={b} grid={cols}x{rows} scale={scale:.2f}")


if __name__ == "__main__":
    name, size, prompt = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    png = os.path.join(ROOT, "host", "sprites", f"{name}.png")
    if not os.path.exists(png) or "--force" in sys.argv:
        generate(prompt, png)
    to_rgb565_header(png, size, name, os.path.join(ROOT, "firmware", "claude_status", f"sprite_{name}.h"))
    print("ok", png)
